version:                                '2'
services:
    apache-php:
        image:                          php:7.2.1-apache
        container_name:                 strobe-apache
        ports:
            - 80:80
        restart:                        always
        volumes:
            - ./DocumentRoot:/var/www/html
        links:
            - 'mariadb'
    mariadb:
        image:                          mariadb:10.1
        container_name:                 strobe-mariadb
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ:                         "Eastern/Toronto"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD:        "HFqjTwMTroo="
            MYSQL_USER:                 'devuser'
            MYSQL_PASSWORD:             'password'
            MYSQL_DATABASE:             'test'
        restart:                        always
    phpmyadmin:
        image:                          phpmyadmin/phpmyadmin
        container_name:                 strobe-phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart:                        always
        ports:
            - 43102:80
        volumes:
          - /sessions
        links:
            - 'mariadb'
volumes:
    mariadb:
